s = set()
print(type(s))

s_from_list = set([1, 2, 3, 4])
print(s_from_list)
print(type(s_from_list))
s.add(1)
s.add(2)
s.remove(2)
s1 = {4, 6}
print(s.isdisjoint(s1))
print(s)
s2=s.union([3,5,4])
print(s2)
s3=s2.intersection([4,5])
print(s3)
print(max(s2))