# Generated by Django 4.0.4 on 2022-05-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_date_alter_message_user_alter_message_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
